package com.composite.cxfserver;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-04-25T17:23:17.373+08:00
 * Generated source version: 3.3.0
 *
 */
@WebServiceClient(name = "AccidentService",
                  wsdlLocation = "http://127.0.0.1:8050/webservice/api/v1/accident?wsdl",
                  targetNamespace = "http://service.cxfserver.composite.com")
public class AccidentService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.cxfserver.composite.com", "AccidentService");
    public final static QName AccidentServiceImplPort = new QName("http://service.cxfserver.composite.com", "AccidentServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8050/webservice/api/v1/accident?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AccidentService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8050/webservice/api/v1/accident?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AccidentService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AccidentService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccidentService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public AccidentService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AccidentService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AccidentService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns AccidentService
     */
    @WebEndpoint(name = "AccidentServiceImplPort")
    public AccidentService getAccidentServiceImplPort() {
        return super.getPort(AccidentServiceImplPort, AccidentService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccidentService
     */
    @WebEndpoint(name = "AccidentServiceImplPort")
    public AccidentService getAccidentServiceImplPort(WebServiceFeature... features) {
        return super.getPort(AccidentServiceImplPort, AccidentService.class, features);
    }

}
