package com.composite.cxfserver;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-04-25T17:23:17.233+08:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://service.cxfserver.composite.com/", name = "AccidentService")
@XmlSeeAlso({ObjectFactory.class})
public interface AccidentService {

    @WebMethod(action = "deleteAccidentAction")
    @RequestWrapper(localName = "deleteAccidentOperation", targetNamespace = "http://service.cxfserver.composite.com/", className = "com.composite.cxfserver.DeleteAccidentOperation")
    @ResponseWrapper(localName = "deleteAccidentOperationResponse", targetNamespace = "http://service.cxfserver.composite.com/", className = "com.composite.cxfserver.DeleteAccidentOperationResponse")
    @WebResult(name = "deleteAccidentResult", targetNamespace = "")
    public com.composite.cxfserver.ResponseBean deleteAccidentOperation(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );

    @WebMethod(action = "acceptAccidentAction")
    @RequestWrapper(localName = "acceptAccidentOperation", targetNamespace = "http://service.cxfserver.composite.com/", className = "com.composite.cxfserver.AcceptAccidentOperation")
    @ResponseWrapper(localName = "acceptAccidentOperationResponse", targetNamespace = "http://service.cxfserver.composite.com/", className = "com.composite.cxfserver.AcceptAccidentOperationResponse")
    @WebResult(name = "acceptAccidentResult", targetNamespace = "")
    public com.composite.cxfserver.ResponseBean acceptAccidentOperation(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );

    @WebMethod(action = "updateAccidentAction")
    @RequestWrapper(localName = "updateAccidentOperation", targetNamespace = "http://service.cxfserver.composite.com/", className = "com.composite.cxfserver.UpdateAccidentOperation")
    @ResponseWrapper(localName = "updateAccidentOperationResponse", targetNamespace = "http://service.cxfserver.composite.com/", className = "com.composite.cxfserver.UpdateAccidentOperationResponse")
    @WebResult(name = "updateAccidentResult", targetNamespace = "")
    public com.composite.cxfserver.ResponseBean updateAccidentOperation(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );
}
