package com.composite.cxfclient.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-03-13T17:14:58.879+08:00
 * Generated source version: 3.3.0
 *
 */
@WebServiceClient(name = "StudentServiceImplService",
                  wsdlLocation = "http://127.0.0.1:8082/webservice/api/v1/student/get?wsdl",
                  targetNamespace = "http://impl.service.cxf.composite.com/")
public class StudentServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.cxf.composite.com/", "StudentServiceImplService");
    public final static QName StudentServiceImplPort = new QName("http://impl.service.cxf.composite.com/", "StudentServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8082/webservice/api/v1/student/get?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(StudentServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8082/webservice/api/v1/student/get?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public StudentServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StudentServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public StudentServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public StudentServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public StudentServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns StudentService
     */
    @WebEndpoint(name = "StudentServiceImplPort")
    public StudentService getStudentServiceImplPort() {
        return super.getPort(StudentServiceImplPort, StudentService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentService
     */
    @WebEndpoint(name = "StudentServiceImplPort")
    public StudentService getStudentServiceImplPort(WebServiceFeature... features) {
        return super.getPort(StudentServiceImplPort, StudentService.class, features);
    }

}
