package com.composite.cxfclient.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-03-22T16:20:58.867+08:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://service.cxf.composite.com/", name = "StudentService")
@XmlSeeAlso({ObjectFactory.class})
public interface StudentService {

    @WebMethod(action = "getStudentAction")
    @RequestWrapper(localName = "getStudentOperation", targetNamespace = "http://service.cxf.composite.com/", className = "com.composite.cxfclient.client.GetStudentOperation")
    @ResponseWrapper(localName = "getStudentOperationResponse", targetNamespace = "http://service.cxf.composite.com/", className = "com.composite.cxfclient.client.GetStudentOperationResponse")
    @WebResult(name = "resultStudent", targetNamespace = "")
    public Student getStudentOperation(
            @WebParam(name = "id", targetNamespace = "http://service.cxf.composite.com/")
                    Integer id
    );

    @WebMethod(action = "getAllStudentAction")
    @RequestWrapper(localName = "getAllStudentOperation", targetNamespace = "http://service.cxf.composite.com/", className = "com.composite.cxfclient.client.GetAllStudentOperation")
    @ResponseWrapper(localName = "getAllStudentOperationResponse", targetNamespace = "http://service.cxf.composite.com/", className = "com.composite.cxfclient.client.GetAllStudentOperationResponse")
    @WebResult(name = "resultAllStudent", targetNamespace = "")
    public Students getAllStudentOperation(
            @WebParam(name = "ids", targetNamespace = "http://service.cxf.composite.com/")
                    String ids
    );
}
